### ISSUE TITLE
Adición de header y menu a la página index

### ISSUE THREAD

**Issue by robertux** [cecylopez/inventario-web#9]
Adición del header de bootstrap mostrando el nombre del usuario logueado, una opción para cambiar contraseña y una opción de logout. 

Agregar también opciones del menú para navegar a las páginas de las funciones principales del sistema

**Comment by cecylopez** [comment]
Para evaluar lo de la contraseña actual me dijiste que tengo que tener dos usuarios verdad?

**Comment by cecylopez** [comment]
Como tengo una pagina html con el formulario de cambio de contraseña entonces en el dropdown solamente redirecciono a esa pagina y en el formulario en vez de un ng-click debo de hacer un ng-submit al igual que en el login?

**Comment by robertux** [comment]
> Para evaluar lo de la contraseña actual me dijiste que tengo que tener dos usuarios verdad?

Ya tenes el usuario sacado de sesión:

`ln 90:		Usuario	usr=(Usuario)req.getSession().getAttribute(USUARIO_SESION);`

Pero ese usuario no tiene la contraseña porque se la borramos luego del login, así que necesitas volver a ir a traer la información del usuario a la base de datos usando la variable repo que ya declaraste:

`ln 92:		UsersRepository repo= new UsersRepository();`

Con esa variable podes hacer  `repo.get(usr.getId))` para traer la contraseña y compararla contra la que te ingresaron usando el `SecurityHelper`.

**Comment by robertux** [comment]
> Como tengo una pagina html con el formulario de cambio de contraseña entonces en el dropdown solamente redirecciono a esa pagina y en el formulario en vez de un ng-click debo de hacer un ng-submit al igual que en el login?

Por el momento deja la página de forma independiente y probala ingresando su URL en el navegador (acordate que la página debe estar dentro de /site/)

Luego te explico cómo hacer para mostrarla desde el menú.

**Comment by cecylopez** [comment]
Ya cambia la contraseña si los parámetros están correctos
Emite un error cuando la contraseña actual esta errónea 

NO genera el error cuando la nueva contraseña no coincide con la repetición del campo 
Al revisar noté que no hace el cambio de contraseña pero no genera el error y se redirecciona a login.html. Por esta razón supongo que algo tengo mal en el Logincontroller. 
No se como limpiar los campos después de generar un error
